# Generated by Django 3.1.1 on 2021-03-28 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manCal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='location',
        ),
    ]
