# Generated by Django 3.1.1 on 2021-03-28 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manCal', '0002_remove_event_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(default='not provided', max_length=200),
        ),
    ]
