# Generated by Django 3.1.1 on 2021-04-01 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manCal', '0004_auto_20210328_1733'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(upload_to='')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manCal.event')),
            ],
        ),
    ]
