# Generated by Django 3.1.1 on 2021-04-05 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manCal', '0008_locations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lunges_set', models.IntegerField()),
                ('Lunges_rep', models.IntegerField()),
                ('Pushups_set', models.IntegerField()),
                ('Pushups_rep', models.IntegerField()),
                ('Squats_set', models.IntegerField()),
                ('Squats_rep', models.IntegerField()),
                ('Burpees_set', models.IntegerField()),
                ('Burpees_rep', models.IntegerField()),
                ('Planks_set', models.IntegerField()),
                ('Planks_rep', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
