# Generated by Django 3.1.1 on 2021-04-25 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manCal', '0009_exercise'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='complited',
            field=models.BooleanField(default=False),
        ),
    ]
